WSS 1단계 미션 해결_서재원
s9hn/WSS_assignment pull request #1
Opened 2023-12-28 20:24 UTC by librarywon

## 기능 요구 사항

- [ ] 내 팔로워 목록을 볼 수 있다.
- 직접 이미지, 이름 리스트 더미데이터를 간단히 만들고 사용한다.
- [ ] 내 정보(이름)를 등록할 수 있다.
- 이름을 작성하지 않으면, 경고 토스트메시지가 나타난다.
- 이름을 작성하고 등록하기 버튼을 누르면, 내 정보뷰에 내 이름이 나타난다.

## 도전 요구 사항

- MBTI 목록을 만들고, 선택할 수 있다.
    - 내 정보(이름과 함께 MBTI가 선택되었을 경우)를 등록할 수 있다.
    - 둘 중 하나라도 작성되지 않으면, 경고 토스트메시지가 나타난다.
    - 둘 모두 작성한 상태로 등록하기 버튼을 누르면, 내 정보뷰에 이름과 MBTI가 나타난다.

## 프로그래밍 요구 사항

- 뷰모델을 이용하지 않는다.
- 다이얼로그는 오직 ‘X’아이콘으로만 닫을 수 있다.

## ScreenShot

https://github.com/s9hn/WSS_assignment/assets/52442547/13ad8748-9a1e-4e0d-b358-20d60c23beac

## To Reviewer.
- 리사이클러뷰 item ui를 그대로 사용하는 것 같아서 팝업에 include 시켜서 사용하였습니다.
- 모든 코드리뷰 감사하고 매운맛 코리도 환영합니다.

2023-12-29 04:02 UTC, s9hn reviewed
이럴 때 build 사용하시면 됩니다

2023-12-29 07:17 UTC, junseo511 approved these changes
새벽 피알 ㄷㄷ 밤에 무슨 일을 하신겁니까 휴먼...

2023-12-29 07:17 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +        val dummyFollowers = listOf(
더미데이터 친구들은 다른 곳에 빼두어도 깔끔할 것 같아요!! 🥳

2023-12-29 07:17 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +        homeBinding.spinnerHomeMBTI.selectedItem.toString().isNullOrBlank()
저는 Toast와 검증을 함께 진행했는데 분리하셨군요,,,!

2023-12-29 07:17 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +                0,
id부여 바람직한 것 같습니당!

2023-12-29 07:17 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/adapter/FollowerAdapter.kt
> +                .into(binding.ivFollowerProfile)
이미지가 url이던데 인터넷 연결이 안되었을때 예외처리 하는 것도 좋아보입니다!

2023-12-29 07:17 UTC, junseo511 commented on WssElixir/app/src/main/res/layout/activity_home.xml
> +        app:layout_constraintTop_toTopOf="@id/tvHomeNameTag" />
이름이 1줄이 넘어가버리면,,, 슬퍼질 것 같습니다,,,!

2023-12-29 07:17 UTC, junseo511 commented on WssElixir/app/src/main/res/values/string_array_mbti_.xml
> +        <item>INTP</item>
저 16개 다박아놨습니다. 즐겁게 줍줍해가시죠 😎

2023-12-29 07:17 UTC, junseo511 commented on WssElixir/app/src/main/res/layout/activity_my_info.xml
> +        tools:text="서재원" />
하나의 텍스트뷰로 표현해도 좋을 것 같아요!

2023-12-29 08:59 UTC, m6z1 reviewed
굿입니다 👍 👍

2023-12-29 08:59 UTC, m6z1 commented on WssElixir/app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
요거슨 미리 추가해두신 건가요 ?

2023-12-29 08:59 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +                makeToast("이름과 MBTI를 입력해주세요")
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-12-29 08:59 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +                navigateToMyInfoActivity()
```suggestion
when {
    checkUserName() && checkUserMBTI() -> makeToast("이름과 MBTI를 입력해주세요")
    checkUserName() -> makeToast("이름을 입력해주세요")
    checkUserMBTI() -> makeToast("MBTI를 선택해주세요")
    else -> navigateToMyInfoActivity()
}
```
when 절을 사용해보시는 건 어떨까요 ? 가독성이 더 좋아질 듯 !

2023-12-29 08:59 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +        }
User 데이터 클래스를 만들어서 이용하는 거 좋군요 ..

2023-12-29 08:59 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +        }
와 with 함수를 이렇게도 사용할 수 있네요 ;; 방금 알아서 인생 조금 손해본 느낌

2023-12-29 08:59 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +    }
오 alertBuilder를 사용하셨네요 굿입니다

2023-12-29 08:59 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/model/User.kt
> +) : Parcelable
직렬화 나도 도전해봐야겠다

2023-12-29 08:59 UTC, m6z1 commented on WssElixir/app/src/main/res/layout/activity_home.xml
> +
이 두 줄 무엇이죠

2023-12-29 08:59 UTC, m6z1 commented on WssElixir/app/src/main/res/layout/activity_my_info.xml
> +        tools:text="서재원" />
왜 하나의 텍스트뷰로 표현해도 좋다고 생각하시나요 !!?? @junseo511

2023-12-29 09:23 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/adapter/FollowerAdapter.kt
> +}
합세 때 준희 오빠한테 코리 받은 부분인데용 
![image](https://github.com/s9hn/WSS_assignment/assets/114990782/80eac830-c40f-4af8-892d-f85157d5ac39)

이런 이유 때문에 inner 클래스는 지양하는 게 좋다고 합니다!! 
한 번 읽어보심 좋을 듯 합니다요
https://thdev.tech/kotlin/2020/11/17/kotlin_effective_11/

2023-12-29 14:52 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +        val dummyFollowers = listOf(
우리가 아직 데이터 레이어를 분리하지 않았기 때문에 같은 뷰에 두었고 companion object로 매번 재생성 되는 경우를 방지하였습니다.

2023-12-29 14:53 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/adapter/FollowerAdapter.kt
> +                .into(binding.ivFollowerProfile)
예외처리 생각 못했는데 아주 좋은 지적입니다!

2023-12-29 14:53 UTC, librarywon commented on WssElixir/app/src/main/res/layout/activity_my_info.xml
> +        tools:text="서재원" />
저도 궁금합니다.

2023-12-29 15:00 UTC, librarywon commented on WssElixir/app/src/main/res/layout/activity_home.xml
> +        app:layout_constraintTop_toTopOf="@id/tvHomeNameTag" />
이것까진 고려하진 않았네요

2023-12-29 16:02 UTC, s9hn requested changes
고생하셨습니다

2023-12-29 16:02 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/myInfo/MyInfoActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
함수 개행 바랍니다.. 불-편

2023-12-29 16:02 UTC, s9hn commented on WssElixir/app/src/main/res/layout/dialog_home.xml
> +    <include
include.. 좋아하시나요 ..?

2023-12-29 18:08 UTC, librarywon commented on WssElixir/app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
HTTP traffic 에러로 사진이 불러와지지 않는줄 알아서 추가하였는데 아니였더라구요!

2023-12-29 18:09 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +                navigateToMyInfoActivity()
매우 좋은것 같습니다 반영하겠습니다.

2023-12-29 18:10 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/myInfo/MyInfoActivity.kt
> +package com.example.wsselixir.presentation.myInfo
반영하겠습니다 크크

2023-12-31 13:12 UTC, librarywon reviewed
코드리뷰 반영하였습니다! 확인 부탁드려요

2023-12-31 15:20 UTC, merged

2023-12-31 16:27 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/adapter/FollowerAdapter.kt
> +    inner class FollowerViewHolder(private val binding: ItemFollowerBinding) :
남겨주신것 처럼 inner class 형식의 뷰홀더는 재사용이 어려울뿐더러, onCreatedViewHolder로 뷰홀더를 생성할 때마다 외부객체 참조가 여러번 일어날 수 있습니다! 
이왕이면 분리 혹은 nested class 사용을 개인적으론 권장합니다!

2023-12-31 16:40 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/home/HomeActivity.kt
> +        Glide.with(applicationContext)
오.. 이부분은 저도 몰랐네요 꿀팁 잘먹고갑니당