[3단계] 서재원 미션 제출합니다
s9hn/WSS_assignment pull request #11
Opened 2024-01-06 12:23 UTC by librarywon

## 기능 요구 사항

- 현재 사용중인 User 리스트와 새로 추가된 더미데이터 리스트를 합쳐서 보여준다.
- 패키지 구분을 통해 ‘ui’ 레이어와 ‘data’ 레이어를 분리해본다.

## 구현 설명
- 레포지토리 패턴을 적용하였습니다.

2024-01-06 13:10 UTC, s9hn requested changes
어떻게 반환시켜야 리스폰스와 엔티티에 대한 의존성을 끊어낼 수 있는지 고민해보세요!
해당 매퍼함수에 대한 컨벤션은 PRND컨벤션에도 소개되어 있습니다.

2024-01-06 13:10 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/data/model/LocalUser.kt
>  import android.os.Parcelable
LocalUser는 data레이어에서 사용되는 모델이 맞나요?
혹여나 클린아키텍처를 사용하여 도메인모듈이 추가되었을 때, 해당 모델을 도메인모듈이 사용하게 되면 어떤 문제가 발생할까요?

2024-01-06 13:10 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/data/mapper/UserToMemberEntityMapper.kt
> +fun UserResponseDto.User.toMemberEntity(): MemberEntity {
해당 모델은 로컬DB에 접근할 때 사용되는 Entity모델입니다. 
데이터레이어에서 사용되는 해당 모델로 래핑하여 다른 레이어에게 전파하면, 다른 레이어는 결국 데이터모델에 대한 의존성을 가질 수 밖에 없습니다.

2024-01-06 13:10 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/data/mapper/UserToMemberEntityMapper.kt
> +fun UserResponseDto.User.toMemberEntity(): MemberEntity {
추가로, 매퍼함수의 네이밍에 대해선 의견이 분분합니다.
구체적인 toDataClass 네이밍을 명시하는 반면, toDomain(), toData() 등 레이어의 목적지로 명명하기도 합니다.
어떤게 옳은 것 같나요?

2024-01-06 13:10 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/detail/DetailViewModel.kt
> +import com.example.wsselixir.data.model.LocalUser
import = 안다 = 의존한다였죠. 
remote를 알고있으며, 객체이름에 Local이 사용된 것으로 보아 local 또한 알고있네요

2024-01-06 13:10 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/home/HomeActivity.kt
> +        HomeViewModelFactory(MemberRepository(NetworkModule.reqresApi,InMemoryMembers()))
이전에 적용했던 것 처럼. 뷰모델 인스턴스도 뷰모델이 스스로 만들어서 받아오게 할 수는 없을까요?

2024-01-06 13:10 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/home/HomeViewModel.kt
> +    private var _followers: MutableLiveData<List<MemberEntity>> =
Local Entity !

2024-01-06 13:10 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/home/HomeViewModelFactory.kt
> +class HomeViewModelFactory(private val memberRepository: MemberRepository) : ViewModelProvider.Factory {
해당 클래스 없이 더욱 쉽게 뷰모델을 생성하는 방법은 없을까요?
공식문서에도 정답이 있습니다!
뷰모델인스턴스는 뷰모델을 통해 받아오도록 하고 액티비티에선 단 한줄이면 뷰모델을 만들 수 있습니다.

2024-01-06 13:10 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/home/adapter/FollowerAdapter.kt
> -    ListAdapter<UserResponseDto.User, FollowerViewHolder>(FollowerDiffCallback) {
이후부턴 모든 뷰에서 리모트 혹은 로컬에 대한 의존성이 생겼습니다.

2024-01-07 12:19 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/data/repository/member/MemberRepository.kt
> +class MemberRepository(
레포지터리 = 저장소 이 개념을 생각 안하고 클릭아키텍처와 뒤섞여서 생각했더라구요! 점차 개념이 명확해지는 것 같습니다 ㅎㅎ

2024-01-07 15:52 UTC, librarywon reviewed
코드리뷰 반영하였습니다!

2024-01-07 16:26 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/data/model/LocalUser.kt
>  import android.os.Parcelable
안드로이드 의존성은 가능한 뷰에서만 사용하는것을 권장합니다! 가 의도였습니다.
해당 모델을 도메인이 사용하게 되면, 가장 순수해야할 도메인이 안드로이드 의존성을 갖게 되겠죠!

2024-01-07 16:31 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/data/model/LocalUser.kt
>  import android.os.Parcelable
`순수해야할 도메인` 인지하였습니다!

2024-01-07 16:39 UTC, s9hn approved these changes
레포는 끝~

2024-01-07 16:39 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/data/repository/member/MemberRepository.kt
> +        val localUsers = InMemoryMembers().memberEntities.toData()
얘도 생성자로 빼주십쇼

2024-01-07 17:21 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/data/repository/member/MemberRepository.kt
> +        val localUsers = InMemoryMembers().memberEntities.toData()
반영하였습니다

2024-01-09 07:06 UTC, merged