junseo511: feat/process01-challenge
s9hn/WSS_assignment pull request #4
Opened 2023-12-29 06:27 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- [Android Elixir 1단계](https://www.notion.so/kimmjabc/1-12651f82ffa9489b8b8b546d1d8a025c)

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯

- [x] MBTI 목록을 만들고, 선택할 수 있다.
    - 내 정보(이름과 함께 MBTI가 선택되었을 경우)를 등록할 수 있다.
    - 둘 중 하나라도 작성되지 않으면, 경고 토스트메시지가 나타난다.
    - 둘 모두 작성한 상태로 등록하기 버튼을 누르면, 내 정보뷰에 이름과 MBTI가 나타난다.
- [x] 직렬화

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/s9hn/WSS_assignment/assets/127238018/d88f7cc7-a3b9-4aa7-9da8-5ead36451773

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

MBTI spinner까지 완료입니당
Parcelize를 사용해서 유저 정보를 저장하는 형식으로 변경되었습니다

2023-12-29 09:38 UTC, m6z1 reviewed
굿 .. listAdapter까지 잘 쓰시는군요

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/AndroidManifest.xml
> +            android:exported="true" />
exported 를 true 로 두신 이유가 있ㅇ르까요 ?

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait"
screenOrientation 까지 ㄷㄷ

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/FollowerAdapter.kt
> +            .into(binding.ivFollowerProfile)
에러 처리 좋군요

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +
ktlint 플러그인 쓰시면 유용합니다 👍

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +            Context.MODE_PRIVATE
오 sharedPreference를 쓰셨군요

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +        val spinner: Spinner = findViewById(R.id.spMainMbti)
뷰바인딩을 사용하고 있으니 뷰바인딩은 어떨까요 ?

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +            }
오호 요런 방법이 있군요

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +    }
요 부분도 더 코드를 짧게 쓸 수 있을 것 같아요!!

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/util/context/ContextExt.kt
> +}
확장함수 사용하기 편하게 잘 해놓으셨네요 👍

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/userinfo/UserActivity.kt
> +    }
텍스트뷰 하나에 끝냈다는 게 이 뜻이군요! 왜 텍스트 뷰 하나에 끝냈는지 궁금합니다!!

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/res/layout/dialog_follower.xml
> +
aㅏ aㅏ

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/res/layout/dialog_follower.xml
> +        app:layout_constraintBottom_toBottomOf="parent" />
제약조건을 수정해서 marginBottom 을 사용하지 않게 해도 될 것 같아요!

2023-12-29 09:38 UTC, m6z1 commented on WssElixir/app/src/main/res/values/array_mbti.xml
> +
쇽샥해갑니다~크크

2023-12-29 13:55 UTC, junseo511 commented on WssElixir/app/src/main/res/layout/dialog_follower.xml
> +
태희가 맛꿀이지예 올린 글 사용해봤는데 생각보다 성능이 애매하군요 🤔

2023-12-29 13:57 UTC, junseo511 commented on WssElixir/app/src/main/AndroidManifest.xml
> +            android:exported="true" />
오호 위에 있는 MainActivity 복사해서 쓰다가 같이 딸려온듯 합니다

2023-12-29 13:57 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +            Context.MODE_PRIVATE
ID를 순차적으로 부여하고 싶었는데 어떻게 해야할지 고민하다가 sharedPreference를 활용했어요!!

2023-12-29 13:58 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +        val spinner: Spinner = findViewById(R.id.spMainMbti)
앗 참고해보겠습니당

2023-12-29 13:58 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +            }
키보드에서 엔터누르기...!

2023-12-29 13:59 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +    }
아 이거 자꾸 까먹네요 감사합니다!!

2023-12-29 14:02 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/userinfo/UserActivity.kt
> +    }
string.xml도 따로 만들어야 하고 만드는김에 변수 넣을 위치까지 두면 좋을 것 같았어요!! 코드를 관리하기가 용이해지고 미약하게 리소스도 줄거든요!!

2023-12-29 14:03 UTC, junseo511 commented on WssElixir/app/src/main/res/layout/dialog_follower.xml
> +        app:layout_constraintBottom_toBottomOf="parent" />
앗 그런가요...? 작은 화면에 대응해보려고 넣어봤습니다!!

2023-12-29 14:10 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +
바로 깔았습니당

2023-12-29 14:33 UTC, m6z1 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/userinfo/UserActivity.kt
> +    }
오호 ... 그렇다면 startstart 와 botbot 을 잘 활용해보면 해결할 수 있을 것 같스무니다

2023-12-29 14:50 UTC, librarywon reviewed
챌린지까지 고생했습니다!

2023-12-29 14:50 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/data/User.kt
> +class User(val id: Int, val name: String, val mbti: String) : Parcelable
직렬화 좋습니다 왜 Serializable를 쓰지 않고 Parcelable을 사용하셨나요? 혹시 생각해보지 않았다면 공부해보는 것도 좋을 것 같습니다.

2023-12-29 14:50 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/FollowerAdapter.kt
> +    private lateinit var follower: Follower
onBind 함수 안에 전부 코드를 작성 하였으니 이제 이 변수는 필요가 없을 듯 싶습니다.

2023-12-29 14:50 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +    }
둘다 적지 않는다면 네임 토스만 뜨는 로직 같습니다

2023-12-29 14:50 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +        val userId = sharedPreferences.getInt("USER_ID", 0) + 1
서버가 해주는 작업을 해주었네요?

2023-12-29 14:50 UTC, librarywon commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/userinfo/UserActivity.kt
> +    private fun printUserInfo(user: User) {
print보다 init 이나 set도 가능하다고 생각합니다!

2023-12-29 14:54 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/data/User.kt
> +class User(val id: Int, val name: String, val mbti: String) : Parcelable
오 저도 아까 두개 검색해서 비교해봤는데 Parcelable이 좀 더 가벼운 친구라고 하더라구요!!

2023-12-29 14:55 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/FollowerAdapter.kt
> +    private lateinit var follower: Follower
아하

2023-12-29 14:55 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +    }
일부러 의도한 부분인데 어떤게 정답인지는 잘 모르겠네요!! 🤔

2023-12-29 14:56 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/main/MainActivity.kt
> +        val userId = sharedPreferences.getInt("USER_ID", 0) + 1
하핫

2023-12-29 14:56 UTC, junseo511 commented on WssElixir/app/src/main/java/com/example/wsselixir/presentation/userinfo/UserActivity.kt
> +    private fun printUserInfo(user: User) {
다들 init을 사용했더라구요! 국룰인가봐요 저도 수정해볼게요

2023-12-29 16:32 UTC, s9hn requested changes
고생하셨습니다

> the extension function is supposed to be compact and limited in scope, and no one expects to see big business logic in these functions.

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/data/User.kt
> +class User(val id: Int, val name: String, val mbti: String) : Parcelable
왜 class로 구현하셨나요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/data/Follower.kt
> +val followers = listOf(
followers를 공유자원으로 두는 이유는 무엇인가요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/FollowerAdapter.kt
> +    ListAdapter<Follower, FollowerViewHolder>(ItemDiffCallback<Follower>(
리스트어댑터를 사용하는 이유는 무엇인가요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/FollowerAdapter.kt
> +    )) {
시그니처의 가독성을 개선할 수는 없을까요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/FollowerAdapter.kt
> +        Glide.with(binding.root)
수신 객체 지정 람다의 역할은 무엇인가요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/FollowerAdapter.kt
> +        itemView.setOnClickListener {
onBind함수가 매번 호출될 때마다 클릭리스너를 세팅해주어야할까요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/FollowerProfileDialog.kt
> +        val dlg = Dialog(context)
> 객체지향 생활체조 원칙 9가지는 다음과 같다.
> 
> 5. 줄여 쓰지 않는다(축약 금지).

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/FollowerProfileDialog.kt
> +class FollowerProfileDialog(private val context: AppCompatActivity) {
AppCompatActivity는 context인가요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/FollowerProfileDialog.kt
> +class FollowerProfileDialog(private val context: AppCompatActivity) {
생성자는 뭘까요? context를 생성자로 받게 되면 어떤 문제가 발생할까요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/FollowerProfileDialog.kt
> +    fun showDialog(follower: Follower) {
다이얼로그를 보여주기만 하는 함수인가요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/MainActivity.kt
> +    private fun initFollowers() {
팔로워를 초기화해준다는게 어떤 일을 하는 함수인가요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/MainActivity.kt
> +    private fun inputProcess() {
무언가 입력하는 함수의 네이밍이라기엔 다소 어색합니다! 
grep.app 사이트를 참고해보세요!

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/MainActivity.kt
> +        if (isNameValid(inputName) && isMbtiValid(selectedMbti)) {
inputProcess 이름과 어울리는 로직일까요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/MainActivity.kt
> +        val spinner: Spinner = findViewById(R.id.spMainMbti)
음..? 바인딩을 안쓴이유가 있나요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/MainActivity.kt
> +        } else {
> 객체지향 생활체조 원칙 9가지는 다음과 같다.
> 
> 2. else 예약어를 쓰지 않는다.

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/MainActivity.kt
> +    private fun navigateToUserActivity(user: User) {
다른 뷰로 이동하는 본 함수가 enroll함수에 필수조건으로 호출되는게 자연스러울까요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/MainActivity.kt
> +        val userId = sharedPreferences.getInt("USER_ID", 0) + 1
shared를 쓰신 이유는 무엇인가요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/userinfo/UserActivity.kt
> +    private fun printUserInfo(user: User) {
정말 유저정보를 print하고있나요?

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/util/context/ContextExt.kt
> +
https://hackernoon.com/using-kotlin-extension-functions-the-good-the-bad-and-the-ugly

2023-12-29 16:32 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/MainActivity.kt
> +            LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false)
xml에도 있지 않나요?

2023-12-30 18:44 UTC, taeheeL commented on WssElixir/app/src/main/res/layout/dialog_follower.xml
> +
슬프네요 ㅠ

2023-12-31 16:46 UTC, s9hn approved these changes

2024-01-01 06:51 UTC, merged

2024-01-01 08:49 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/FollowerAdapter.kt
> +    ListAdapter<Follower, FollowerViewHolder>(ItemDiffCallback<Follower>(
ListAdapter는 무조건적으로 Recyclerview Adapter보다 좋다고는 할 수 없을 것 같아요!
각각의 장단점과 적재적소 상황을 잘 파악해봅시다 !

2024-01-01 08:50 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/ui/main/FollowerAdapter.kt
> +        Glide.with(binding.root)
https://www.youtube.com/watch?v=rRjvHKd0ci0

진짜 설명잘해주니까 심심할 때 구경가보시죠

2024-01-01 08:55 UTC, s9hn commented on WssElixir/app/src/main/java/com/example/wsselixir/util/context/ContextExt.kt
> +
그건 한번 웹소소를 직접 해보면서 깨달아보시죠 ㅋㅋ